import abc

class LineHandler(abc.ABC):

    @abc.abstractmethod
    def handle_line                 (self, line:str): ...
    @abc.abstractmethod
    def handle_eof                  (self): ...

class PartsHandler(LineHandler):

    @abc.abstractmethod
    def handle_part                 (self, part:str): ...
    @abc.abstractmethod
    def handle_comment              (self, text:str): ...
    @abc.abstractmethod
    def handle_spacing              (self, spacing:str): ...
    @abc.abstractmethod
    def handle_newline              (self): ...
    
from .. import model

class StreamHandler(abc.ABC): 

    @abc.abstractmethod
    def handle_package           (self, package:model.Package):  ...
    @abc.abstractmethod
    def handle_import            (self, import_:model.Import):  ...
    @abc.abstractmethod
    def handle_annotation        (self, annot:model.Annotation):   ...
    @abc.abstractmethod
    def handle_class             (self, class_:model.Class):  ...
    @abc.abstractmethod
    def handle_class_end         (self, class_end:model.ClassEnd):  ...
    @abc.abstractmethod
    def handle_static_constructor(self, sconstr:model.StaticConstructor):  ...
    @abc.abstractmethod
    def handle_constructor       (self, constr:model.Constructor):  ...
    @abc.abstractmethod
    def handle_attr              (self, attr:model.Attribute):  ...
    @abc.abstractmethod
    def handle_method            (self, method:model.Method):  ...
    @abc.abstractmethod
    def handle_enum_value        (self, enum:model.EnumValue):  ...
    @abc.abstractmethod
    def handle_comment           (self, comment:model.Comment): ...

from . import body, callargs, generics, signature, type, annotation
