from .. import decl as _decl
from ... import model as _model

import abc as _abc
    
class Handler(_abc.ABC):

    @_abc.abstractmethod
    def handle_package      (self, package      :_decl.PackageDeclaration):  ...
    @_abc.abstractmethod
    def handle_import       (self, import_      :_decl.ImportDeclaration):  ...
    @_abc.abstractmethod
    def handle_class        (self, class_       :_decl.ClassHeaderDeclaration):  ...
    @_abc.abstractmethod
    def handle_class_end    (self):  ...
    @_abc.abstractmethod
    def handle_initializer  (self, initializer  :_decl.InitializerDeclaration):  ...
    @_abc.abstractmethod
    def handle_constructor  (self, constructor  :_decl.ConstructorDeclaration):  ...
    @_abc.abstractmethod
    def handle_attribute    (self, attribute    :_decl.AttributeDeclaration):  ...
    @_abc.abstractmethod
    def handle_method       (self, method       :_decl.MethodDeclaration):  ...
    @_abc.abstractmethod
    def handle_enum_value   (self, enumvalue    :_decl.EnumValueDeclaration):  ...
    @_abc.abstractmethod
    def handle_comment      (self, comment      :_model.Comment): ...
