import typing

from .   import Handler, PackageDeclaration
from ... import model

class ClassBuilder(Handler):

    @typing.override
    def handle_package      (self, package:PackageDeclaration):  ...
    @typing.override
    def handle_import       (self, import_:model.Import):  ...
    @typing.override
    def handle_class        (self, class_:model.ClassHeader):  ...
    @typing.override
    def handle_class_end    (self):  ...
    @typing.override
    def handle_initializer  (self, initializer:model.Initializer):  ...
    @typing.override
    def handle_constructor  (self, constr:model.Constructor):  ...
    @typing.override
    def handle_attr         (self, attr:model.Attribute):  ...
    @typing.override
    def handle_method       (self, method:model.Method):  ...
    @typing.override
    def handle_enum_value   (self, enum:model.EnumValue):  ...
    @typing.override
    def handle_comment      (self, comment:model.Comment): ...
